package com.codeglide.core.rte.render;

public enum ActionFlag {
	AUTOSUBMIT, DATETIME, LOCALMAILTO, INVALIDURI, LOADEXTIMG, LOADDYNAMIC, REPLACEBODY, REMOVESTYLE, SORTDESC, CLICKABLE, DOUBLECLICKABLE,
	GROUPCOLLAPSED, GROUPHIDDEN, ALLOWMULTIPLE, CLOSABLE, BEFORECLOSABE, EDITABLE, COLLAPSIBLE, RESIZABLE, DRAGGABLE, REQUIRED,
	PASSWORDFIELD, BORDER, RELOADABLE, SPLIT, LABELSONTOP, CHECKED, TEMPLATE
}
