package com.codeglide.core.rte.render;

public enum ActionParameter {
	ID, NAME, VALUE, ON, OFF, PAGESIZE, DDGROUP, SORTBY, GROUPBY, TEMPLATE, TITLE, MESSAGE, TYPE, TARGET, PAYLOAD, INPUTLIST, /*WINDOW_ID,
	PANEL_ID,*/ WIDTH, HEIGHT, PADDING, LAYOUT, ICON, REGION, MARGINS, GROUP, TOOLTIP, BUTTONS, BACKGROUNDCOLOR
}
