package com.codeglide.core.rte.render;

public enum ActionType {
	TEXTFIELD, CHECKBOX, DATEFIELD, COLORPICKER, LABEL, LABELFIELD, RICHTEXT, IMAGESELECTOR, MENU, TOGGLER, SEPARATOR, BUTTONS, TOPBAR, BOTTOMBAR,
	SELECT, RADIOGROUP, MULTISELECT, ITEMSELECTOR, SELECTREMOTE, GRID, DATAVIEW, TREE, SET_SESSION, SHOW_MESSAGE, SHOW_ALERT, SHOW_FILE_DIALOG,
	BUTTON, ITEM_ADD, FORM_SUBMIT, FORM_VALIDATE, COMPONENT_COMMIT, OPEN_WINDOW, REMOVE_COMPONENT, ADD_COMPONENT, PANEL, CONTENTS, RELOAD_COMPONENT,
	CLEAR_PANEL, CLOSE_WINDOW, ITEM_REMOVE, ITEM_RELOAD, ITEM_RENAME, ADDCSS, FORM, TABPANEL, FIELDSET, INIT, WINDOW, ACCORDIONPANEL,
	COLUMNPANEL, REGIONPANEL, REPLACE_COMPONENT, SAVE_COOKIE, ITEM
}
